#!/bin/sh

PROJECTROOT=`echo $(cd ${0%/*}/../../ && pwd -P)`/

HASH=$(git log -1 HEAD --pretty="%H")
PROJECT_SLUG=$(basename $PROJECTROOT)

#let's run sismo
$(brew --prefix josegonzalez/php/$PHP)/bin/php ~/Work/Sismo/sismo --quiet build $PROJECT_SLUG $HASH &
